server:
  port: 1000

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
      password: ${REDIS_PASSWORD}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:${NACOS_PORT}
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
    gateway:
      discovery:
        locator:
          enabled: true    # 动态路由，从注册中心根据微服务的名称获得目标节点的地址
      routes:              # 配置路由规则（数组/list）
        - id: authRoute    # 每一项路由规则都有一个唯一的id编号，可以自定义
          uri: lb://auth-service   # lb=负载均衡，会动态寻址
          predicates:
            - Path=/a/**, /passport/**
        - id: fileRoute
          uri: lb://file-service
          predicates:
            - Path=/f/**, /file/**, /static/**
        - id: mainRoute
          uri: lb://main-service
          predicates:
            - Path=/m/**, /userinfo/**, /friendRequest/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true