server:
  port: 55

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:${NACOS_PORT}
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}

image:
  storage:
    path: ${IMAGE_STORAGE_PATH}

minio:
  accessKey: ${MINIO_USERNAME}
  secretKey: ${MINIO_PASSWORD}
  endpoint: ${MINIO_URL}
  fileHost: ${MINIO_URL}
  bucketName: ${MINIO_BUCKET_NAME}

qr-code:
  filePath: ${QRCODE_LOCAL_PATH}

chat:
  video:
    file-path: ${CHAT_VIDEO_LOCAL_PATH}

baidu:
  speech-to-text:
    app-id: ${BAIDU_SPEECH_TO_TEXT_APP_ID}
    api-key: ${BAIDU_SPEECH_TO_TEXT_API_KEY}
    secret-key: ${BAIDU_SPEECH_TO_TEXT_SECRET_KEY}