server:
  port: 55

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:${NACOS_PORT}
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}

image:
  storage:
    path: ${IMAGE_STORAGE_PATH}